### ISSUE TITLE
Incorrect Pip Value on Micro Futures 

### ISSUE THREAD

**Issue by GitHubTrader** [EarnForex/PositionSizeCalculator#10]
Hello,

In version 2.27 this worked correctly in version 2.33 the Pip Value is wrong. I'm not much of a coder but I am trying to find the difference or what changed to make this happen, so if I find I'll post again. If someone has time to look into this it would be appreciated.

I've included screen shots showing the difference. The left side is the correct Pip value. I also imagine this may mess up the SL/TP on futures like S&P and Nasdaq as the SL/TP has to be set at .25 levels. I haven't tested to see if the SL/TP is properly place as of yet.

This is MT5 with Futures broker ampfutures 

![v227_v233_01](https://user-images.githubusercontent.com/78833383/107456109-3d306880-6b15-11eb-8f53-62035ca417a7.PNG)

![v227_v233_02](https://user-images.githubusercontent.com/78833383/107456122-428db300-6b15-11eb-9136-b75ef4a97475.PNG)

**Comment by GitHubTrader** [comment]
Hello,

Do you have a google voice or some other number capable of receiving
texts,  I can use to setup an account?

The require this and verify it one time.



Thanks

**Comment by EarnForex** [comment]
What's the email address I can send you my phone number to?

**Comment by GitHubTrader** [comment]
It's strange that you aren't able to setup an account as I know they have
used from around the world.

I ment to mention I tried applying for an account using your email address
check your email to see if you received anything.

**Comment by EarnForex** [comment]
OK, thanks to @GitHubTrader I now have a working demo account.
I've looked into the issue with incorrect pip value and position size calculation. It seems, the problem is caused by either incorrect return of the TickValue for this symbols from the trading server or by incorrect MQL5 documentation on the calculation method (I don't remember if I tested Exchange Futures symbols with any other brokers). Most likely, it is the former as the TickValue right now returns 0.5, while this symbol is a $5 futures where $1 movement in the underlying index should cost $5.

Anyway, a rough fix can be applied by replacing line 5019 in PositionSizeCalculator.mqh:
`      if ((CalcMode == SYMBOL_CALC_MODE_FUTURES) || (CalcMode == SYMBOL_CALC_MODE_EXCH_FUTURES) || (CalcMode == SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS))`
with:
`      if ((CalcMode == SYMBOL_CALC_MODE_FUTURES) /*|| (CalcMode == SYMBOL_CALC_MODE_EXCH_FUTURES)*/ || (CalcMode == SYMBOL_CALC_MODE_EXCH_FUTURES_FORTS))`

I will later look into the issue with the spread.

**Comment by EarnForex** [comment]
OK, I've looked into the spread issue, and it doesn't seem incorrect to me. The spread is calculated as Ask - Bid, which is exactly 25 points here:
![spread](https://user-images.githubusercontent.com/48102957/107761411-ff5d5b00-6d33-11eb-9afc-e873cdf5d211.png)

Please let me know if I am missing something.

**Comment by EarnForex** [comment]
Solved in 2.34.
