### ISSUE TITLE
SL line stuck and not moving with current price

### ISSUE THREAD

**Issue by domdonit13** [EarnForex/PositionSizeCalculator#67]
Hi, I set a stop loss of 100 points but sometimes the SL line gets stuck and this value changes to a smaller stop loss. I've already set the Max/Min Entry SL distance and the Default stop-loss value, in points to the 100 points that I want but the same keeps happening, any ideia?

**Comment by EarnForex** [comment]
Hello!

So, you are running the PS EA (by the way, is it on MT4 or on MT5?) with SLDistanceInPoints set to true and DefaultSL set to 100. And normally, the SL remains equal 100, but sometimes it changes its value, right? Does that happen with the Instant order type or with the Pending order type? Could this be happening because you accidentally move the SL line on the chart? Does clicking the SL button reset it to the default value (100)?

**Comment by domdonit13** [comment]
Hello, My platform is MT5.

Yes, SLDistanceInPoints is set to true and DefaultSL is set to 100. That's right, the stop loss changes sometimes and then it returns to 100 again, then changes again and so on (btw about the TP it is always fixed and I'm not having problem with it). As I noticed, its happening only with Instant orders. The line is always deselected and when a click on **SL, points:** it resets to 100 again.

**Comment by EarnForex** [comment]
Should be fixed in 3.04. Thank you!
